version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: yarn start
    ports:
      - "3000:3000"
    volumes: 
      - app-sync:/usr/src/app:nocopy
    command: /bin/sh
    stdin_open: true
    tty: true
  db:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
volumes:
  app-sync:
    external: true
